### ISSUE TITLE
Does this method support dynamic crafter?

### ISSUE THREAD

**Issue by trouble-maker007** [mihirp1998/VADER#3]

**Comment by xpeng** [comment]
same question

**Comment by QinOwen** [comment]
Hi. This method should be compatible with DynamiCrafter, as we've successfully implemented it on one of the I2V models (Stable Video Diffusion). However, as noted in #6 , trade-offs may limit the extent of improvement. If you would like to apply this method to DynamiCrafter, we have provided [VideoCrafter tutorial](https://github.com/mihirp1998/VADER/blob/master/VADER-VideoCrafter/readme.md), in which we provide a step-by-step guide to help you understand the necessary modifications for VideoCrafter2 in the last section. You may get some ideas on how to modify the DynamiCrafter codes accordingly.
