### ISSUE TITLE
Ensure download metrics work on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [mihirp1998/VADER#5]
Hi,

Niels here from the open-source team at Hugging Face. It's great to see you're releasing models on HF, which are also linked to the paper page: https://huggingface.co/papers/2407.08737.

I see that currently download stats aren't working for your model. This is due to the model repository containing various models, which do not contain a config.json file. See here for more info: https://huggingface.co/docs/hub/models-download-stats.

There are a few options here to make them work:

1) either we can open a PR on the huggingface.js repository to view "VADER" as a library, for which we add dedicated support. See this PR as an example: https://github.com/huggingface/huggingface.js/pull/784
2) one could leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/en/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) to push model checkpoints to separate model repositories, each containing a config.json and safetensors file.

Usually we recommend to have a single repository per checkpoint.

Let me know what you prefer, and whether you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by QinOwen** [comment]
> Hi,
> 
> Niels here from the open-source team at Hugging Face. It's great to see you're releasing models on HF, which are also linked to the paper page: https://huggingface.co/papers/2407.08737.
> 
> I see that currently download stats aren't working for your model. This is due to the model repository containing various models, which do not contain a config.json file. See here for more info: https://huggingface.co/docs/hub/models-download-stats.
> 
> There are a few options here to make them work:
> 
> 1. either we can open a PR on the huggingface.js repository to view "VADER" as a library, for which we add dedicated support. See this PR as an example: [Add MeshAnything library huggingface/huggingface.js#784](https://github.com/huggingface/huggingface.js/pull/784)
> 2. one could leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/en/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) to push model checkpoints to separate model repositories, each containing a config.json and safetensors file.
> 
> Usually we recommend to have a single repository per checkpoint.
> 
> Let me know what you prefer, and whether you need any help regarding this!
> 
> Cheers,
> 
> Niels ML Engineer @ HF 🤗

Hi, thank you for the reminder. I have split the repository into two separate repositories and added a fake empty config.json file for each. Now the download stats seem to work.

**Comment by NielsRogge** [comment]
Great! It looks like the downloads will indeed start to work
