### ISSUE TITLE
does this work for any I2V model?

### ISSUE THREAD

**Issue by SkylerZheng** [mihirp1998/VADER#6]
wondering if reward model will be helpful for any I2V models?

**Comment by SkylerZheng** [comment]
i saw you mentioned SVD relevant work, is there any plan to release the Adaptation of Stable Video Diffusion Image2Video Model?

**Comment by QinOwen** [comment]
> wondering if reward model will be helpful for any I2V models?

Hi. We have implemented our method on Stable Video Diffusion and observed an improvement in performance. However, I believe the improvement might not be significant for the I2V model. The I2V model ideally needs to generate a video maintaining consistency with the provided image; however, the gradient will adjust the I2V model to cater to the reward model's taste (e.g. style). This tradeoff results in a relatively lower overall improvement.
