### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED  

### ISSUE THREAD

**Issue by yyxisgreat** [mihirp1998/VADER#8]
Hi,this is a great job!
But I got into some troubles. 
After downloading all the models and installing the environment,I ran the scripts run_text2video_inference.sh and got following warnings and   errors.I'm sure I didn't revise the code and set the accelerate correctly.What should I do? Thanks for your willingness to help!
![image](https://github.com/user-attachments/assets/0452d22e-b418-4407-9e3a-83215c72b057)

**Comment by yyxisgreat** [comment]
Additionally,I successfully ran the code on the day before yesterday.That was strange

**Comment by mihirp1998** [comment]
can u check if it's a OOM error, as mentioned below

https://discuss.pytorch.org/t/cudnn-error-cudnn-status-not-supported-this-error-may-appear-if-you-passed-in-a-non-contiguous-input/86357

also double check if cudnn is installed:

https://stackoverflow.com/questions/31326015/how-to-verify-cudnn-installation

**Comment by yyxisgreat** [comment]
When I set torch.backends.cudnn.enabled = False,it all went well.Thanks for your responce!
